// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.WebApi.Context;

#nullable disable

namespace Server.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231120184814_mg1")]
    partial class mg1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.WebApi.Models.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f4d1d04-c42a-4b57-ae8c-b7ab7b7006a7"),
                            Date = "09.2011 - 08.2013",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dolor felis, eu ultrices elit molestie.",
                            Title = "Visual Art",
                            Year = "2 Years"
                        },
                        new
                        {
                            Id = new Guid("c23d48c6-b8f5-4c92-acb6-fbd6db146f56"),
                            Date = "09.2011 - 08.2013",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dolor felis, eu ultrices elit molestie.",
                            Title = "Visual Art",
                            Year = "2 Years"
                        });
                });

            modelBuilder.Entity("Server.WebApi.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c32efe08-95eb-4def-bdf4-724e513939cd"),
                            CoverImageUrl = "project1.png",
                            Name = "e-Muhasebe Projesi"
                        },
                        new
                        {
                            Id = new Guid("82b4b5fa-0604-4f4f-b4d8-968d53041f01"),
                            CoverImageUrl = "project2.png",
                            Name = "e-Finans Projesi"
                        },
                        new
                        {
                            Id = new Guid("13337844-51a3-4bd1-a77c-1ebafd533eec"),
                            CoverImageUrl = "project3.png",
                            Name = "My Portfolio Projesi"
                        });
                });

            modelBuilder.Entity("Server.WebApi.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec766cb5-6ccb-417e-b8c1-ccfcc5c75c2e"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/.NET_Core_Logo.svg/2048px-.NET_Core_Logo.svg.png",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("6a2c4bb6-fb6e-4a6c-ad18-c009ae55590c"),
                            ImageUrl = "https://blog.ninja-squad.com/assets/images/angular_gradient.png",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("504d00ca-ad1a-464d-9ada-0e2c9ee872ea"),
                            ImageUrl = "https://pluralsight2.imgix.net/paths/images/domain-driven-design-6d10f953a0.png",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("03c75630-dc09-4e12-9dec-c417c959d791"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/e/ea/Docker_%28container_engine%29_logo_%28cropped%29.png",
                            Order = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
