// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.WebApi.Context;

#nullable disable

namespace Server.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.WebApi.Models.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9248301-4ce0-495b-b906-a7bc17dab60d"),
                            Date = "09.2011 - 08.2013",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dolor felis, eu ultrices elit molestie.",
                            Title = "Visual Art",
                            Year = "2 Years"
                        },
                        new
                        {
                            Id = new Guid("62d8203e-e8d2-4ac2-b0f1-d0d6019b2929"),
                            Date = "09.2011 - 08.2013",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus dolor felis, eu ultrices elit molestie.",
                            Title = "Visual Art",
                            Year = "2 Years"
                        });
                });

            modelBuilder.Entity("Server.WebApi.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4de1544d-4ff9-4b32-a6ed-83737105fae3"),
                            CoverImageUrl = "project1.png",
                            Name = "e-Muhasebe Projesi"
                        },
                        new
                        {
                            Id = new Guid("57627ddd-3d20-4750-9a35-0cc4a9e6e457"),
                            CoverImageUrl = "project2.png",
                            Name = "e-Finans Projesi"
                        },
                        new
                        {
                            Id = new Guid("6a0cf375-86cf-4bb2-929f-118ea40aec27"),
                            CoverImageUrl = "project3.png",
                            Name = "My Portfolio Projesi"
                        });
                });

            modelBuilder.Entity("Server.WebApi.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ccf9baf7-ff88-4f54-815c-df31019b1a81"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/.NET_Core_Logo.svg/2048px-.NET_Core_Logo.svg.png",
                            Order = 1
                        },
                        new
                        {
                            Id = new Guid("ede82b51-ce69-4fd2-853c-64b8f8dd4a05"),
                            ImageUrl = "https://blog.ninja-squad.com/assets/images/angular_gradient.png",
                            Order = 2
                        },
                        new
                        {
                            Id = new Guid("479a49ef-2010-4793-9fc9-a9094f4ac186"),
                            ImageUrl = "https://pluralsight2.imgix.net/paths/images/domain-driven-design-6d10f953a0.png",
                            Order = 3
                        },
                        new
                        {
                            Id = new Guid("ef090539-d04c-4a58-a4de-188f28241343"),
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/e/ea/Docker_%28container_engine%29_logo_%28cropped%29.png",
                            Order = 4
                        });
                });

            modelBuilder.Entity("Server.WebApi.Models.SocialMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a27c71ee-8b9e-4860-a79d-a236fe93cb08"),
                            Icon = "fa-brands fa-linkedin fs-30",
                            Link = "https://www.linkedin.com/in/taner-saydam-b26336222/",
                            Name = "LinkedIn"
                        },
                        new
                        {
                            Id = new Guid("8747e3bd-67db-4029-9969-0b1ff33415c6"),
                            Icon = "fa-brands fa-youtube fs-30",
                            Link = "https://www.youtube.com/channel/UC6Pw9YDMHq3EeNhIF8FMemw",
                            Name = "Youtube"
                        },
                        new
                        {
                            Id = new Guid("e50fdbb6-9846-44e3-93a2-248df1546ea2"),
                            Icon = "fa-brands fa-github fs-30",
                            Link = "https://github.com/TanerSaydam",
                            Name = "GitHub"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
